### ISSUE TITLE
http / https

### ISSUE THREAD

**Issue by MrJinx2015** [Spuds/SMF-Google-Member-Map#7]
I had a small problem installing this on a https only site. All the google content was loaded from http, which prevented some scripts form loading.
I replaced all http urls to https. However, chart.apis.google.com didn't work over https.
The new url is chart.googleapis.com which has a valid ssl ceriticate. After changing this, the mod works fine!

**Comment by Spuds** [comment]
Thanks for the report .... all those urls should probably be changed to be schemaless URLs.  Will do on the next update.
